include: package:flutter_lints/flutter.yaml

linter:
  rules:
    cancel_subscriptions: true
    always_use_package_imports: true
    always_specify_types: true
    directives_ordering: true
    eol_at_end_of_file: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    unawaited_futures: true
    sort_pub_dependencies: true
    prefer_expression_function_bodies: true
